### PR TITLE
Create a reproducible repo.

### PR DESCRIPTION
**Pull request by lapo-luchini**
As stated in [Reproducible builds in FreeBSD](https://www.bsdcan.org/2016/schedule/attachments/375_2016-06-11-BSDCan-2016-Reproducible-Builds.pdf) `bsdtar` doesn't allow changing mtime, so I frist added a line to do this:

```
cd ${REPO_DIR} && ${FIND} . -print0 | xargs -0 touch -d 2022-08-08T20:40:04Z
```

This is not enough as file traversal order changes from time to time; to solve this I used `find -s` to produce a sorted file list:

```
cd ${WRKDIR} && \
${FIND} -s repository/ -print >list.txt && \
${TAR} czf ${DISTDIR}/apache-${PORTNAME}-${DISTVERSION}-repo.tar.gz -nT list.txt
```

Still not enough, as `gzip` header includes a timestamp; this can be solved by using [`gzip -n`](https://www.freebsd.org/cgi/man.cgi?query=gzip&sektion=1) but instead I tried two approaches and it seems to work fine with both:
1. using `7zz` (always sorts traversal order, so `list.txt` is not needed) `7zz a -mx9 ${DISTDIR}/apache-${PORTNAME}-${DISTVERSION}-repo.7z repository/`
2. using `xz` `${TAR} cJf ${DISTDIR}/apache-${PORTNAME}-${DISTVERSION}-repo.tar.xz -nT list.txt`

I decided for the latter as it is included in the base system.

### CODE REVIEW

**Comment by lapo-luchini** [comment]
As stated in [PR 265478](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265478) it seems to need more testing in poudriere.
I'll try in the future, but I won't be able to in the next 3 weeks.

**Comment by lapo-luchini** [comment]
I get the same error I get in the "4.1 upgrade" branch.

```
BUILD FAILED
/wrkdirs/usr/ports/databases/cassandra4/work/apache-cassandra-4.1.0-src/.build/build-resolver.xml:204: java.net.UnknownHostException: files.pythonhosted.org
```

As far as I can tell it's a different Maven repo (use by the sigar sub-project, I think) to connect to and cache…?

**Comment by polo-language** [comment]
> I get the same error I get in the "4.1 upgrade" branch.
> 
> ```
> BUILD FAILED
> /wrkdirs/usr/ports/databases/cassandra4/work/apache-cassandra-4.1.0-src/.build/build-resolver.xml:204: java.net.UnknownHostException: files.pythonhosted.org
> ```
> 
> As far as I can tell it's a different Maven repo (use by the sigar sub-project, I think) to connect to and cache…?

Seem to be using the 4.1 source here too: "apache-cassandra-4.1.0-src". Do you get the same error with the 4.0.5 source?

**Comment by lapo-luchini** [comment]
Whoops, I forgot to copy the new folder to `poudriere` folder. 😇
Launching a new build…

**Comment by lapo-luchini** [comment]
I'm stuck here: it correctly fetches, it correctly generates the repo file, it correctly `ls -al` it… and just after it says it cannot be found!

```
BUILD SUCCESSFUL
Total time: 15 seconds
cd /wrkdirs/usr/ports/databases/cassandra4/work/repository && /usr/bin/find . -type f -name "*.repositories" -a -exec /usr/bin/sed -i '' -e '2s,.*,Mon Aug 08 20:40:04 CEST 2022,' {} +
cd /wrkdirs/usr/ports/databases/cassandra4/work && /usr/sbin/mtree -cbnSp repository | /usr/sbin/mtree -C | /usr/bin/sed  -e 's:time=[0-9.]*:time=0.000000000:'  -e 's:\([gu]id\)=[0-9]*:\1=0:g'  -e 's:flags=.*:flags=none:'  -e 's:^\.:./repository:'  > maven-offline-cache.mtree
cd /wrkdirs/usr/ports/databases/cassandra4/work && /usr/bin/tar cJf /portdistfiles//apache-cassandra-4.0.5-repo.tar.xz  @maven-offline-cache.mtree
ls -al /portdistfiles//apache-cassandra-4.0.5-repo.tar.xz
-rw-r--r--  1 root  wheel  78033936 Mar  8 19:46 /portdistfiles//apache-cassandra-4.0.5-repo.tar.xz
=> apache-cassandra-4.0.5-repo.tar.xz doesn't seem to exist in /portdistfiles/.
===> /!\ Warning /!\
     The :repo group used for apache-cassandra-4.0.5-repo.tar.xz is missing
     from MASTER_SITES. Check for typos, or errors.
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/apache-cassandra-4.0.5-repo.tar.xz
fetch: http://distcache.FreeBSD.org/ports-distfiles/apache-cassandra-4.0.5-repo.tar.xz: Not Found
=> Couldn't fetch it - please try to retrieve this
=> port manually into /portdistfiles/ and try again.
```

**Comment by lapo-luchini** [comment]
I wonder about this: doesn't it contain zstd JNI stuff?
It probably isn't recognized because it's inside a `.jar`.
```
===>   Registering installation for cassandra4-4.0.5
pkg-static: DEVELOPER_MODE: Notice: arch "FreeBSD:13:amd64" -- no architecture specific files found:
**** could this package use a wildcard architecture?
```

**Comment by lapo-luchini** [comment]
@polo-language this seems to compile fine!

**Comment by polo-language** [comment]
> I wonder about this: doesn't it contain zstd JNI stuff? It probably isn't recognized because it's inside a `.jar`.
> 
> ```
> ===>   Registering installation for cassandra4-4.0.5
> pkg-static: DEVELOPER_MODE: Notice: arch "FreeBSD:13:amd64" -- no architecture specific files found:
> **** could this package use a wildcard architecture?
> ```

Regarding the architecture specific files and ZSTD, you've lost the i386 distfile checksum. Running `make makesum` wipes out any unused distfiles. Since the ZSTD distfiles are arch-specific, this'll remove the i386 version from distinfo when run on amd64. Needs to be pasted back in. Cassandra really isn't designed to work on i386 (just due to memory limitations) on any platform, so I'm not sure how long we'll keep this. But it's easier to keep it than not at the moment.

**Comment by lapo-luchini** [comment]
This has been committed upstream. 🎉
Do you prefer to merge this PR to reflect this, or merge manually?

**Pull request merged**
